from __future__ import annotations

from pathlib import Path

from .context_builder import build_context_pack
from .storage import Store

TARGET_FILES = {
    "claude": "CLAUDE.md",
    "agents": "AGENTS.md",
    "codex": ".codex/instructions.md",
    "gemini": "GEMINI.md",
    "cursor": ".cursor/rules/agentflow.mdc",
}

HEADER = """<!-- Generated by AgentFlowDesk. Edit the task in .agentflow/tasks.json or regenerate with agentflow export. -->\n\n"""


def export_context(store: Store, task_id: str, targets: list[str], output_root: Path | None = None,
                   force: bool = False) -> list[Path]:
    context_dir = build_context_pack(store, task_id)
    context = (context_dir / "context-pack.md").read_text(encoding="utf-8")
    root = output_root or store.root
    written: list[Path] = []
    for target in targets:
        if target not in TARGET_FILES:
            raise ValueError(f"Unknown export target: {target}. Valid targets: {', '.join(TARGET_FILES)}")
        out = root / TARGET_FILES[target]
        if out.exists() and not force:
            raise FileExistsError(f"Refusing to overwrite {out}. Use --force to overwrite.")
        out.parent.mkdir(parents=True, exist_ok=True)
        if target == "cursor":
            content = HEADER + "---\ndescription: AgentFlowDesk task context\nalwaysApply: true\n---\n\n" + context
        else:
            content = HEADER + context
        out.write_text(content, encoding="utf-8")
        written.append(out)
    return written
